services:
  chrome:
    build:
      context: .
      dockerfile: docker/Dockerfile.chrome
    command: npm run test:chrome
    volumes:
      - ./allure-results:/app/allure-results

  firefox:
    build:
      context: .
      dockerfile: docker/Dockerfile.firefox
    command: npm run test:firefox
    volumes:
      - ./allure-results:/app/allure-results