FROM selenium/standalone-chrome:134.0-20250323

USER root

RUN apt-get update && \
    apt-get install -y nodejs npm

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN chown -R seluser:seluser /app

USER seluser

CMD ["npm", "run", "test:chrome"]